# creat eks cluster using an existing vpc, it also creat an manage group and an unmange group
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: aloda-test
  region: us-east-1 # set the cluster resource region
  version: "1.23"   # set the eks version
vpc:
  id: "vpc-0ebbfed6857431aef" #replace your vpc id
  cidr: "10.2.0.0/16"  #must match CIDR used by the given VPC
  subnets:
    public:
      us-east-1a:
        id: "subnet-0f1a3c5cbfd9708ab"
        cidr: "10.2.0.0/20"
      us-east-1b:
        id: "subnet-0c70b946820319511"
        cidr: "10.2.16.0/20"
      us-east-1c:
        id: "subnet-022a89c2dd2e976dd"
        cidr: "10.2.32.0/20"
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3.small
  minSize: 2
  desiredCapacity: 2
  maxSize: 4
  volumeSize: 30
  volumeType: gp3
  spot: true
  privateNetworking: false
  ssh:
    publicKeyName: aloda-us-east-1
