---
# custom-index-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Nginx Pod</title>
    </head>
    <body>
        <h1>Welcome to Nginx Pod!</h1>
        <p>Pod IP: ${POD_IP}</p>
    </body>
    </html>
  # rest.properties.template: |
  #   # Put your REST properties here
  #   # Example:
  #   # endpoint = http://example.com/api
  #   endpoint = {{POD_IP}}